development:
  skip_collaboration:
    skip_url: "http://localhost:3000/"
    secret_key: change-me

test:
  skip_collaboration:
    skip_url: "http://test.openskip.org"
    secret_key: "hogehogehogehoge"
