development:
  skip_collaboration:
    skip_url: "http://test.openskip.org.local"
    secret_key: "hogehogehogehoge"
    fulltext_search:
      endpoint:  "/search/full_text_search"
      query_name: "full_text_query"
    fixed_op:
      # disabled: true
      fixed_openid_server_url: "http://localhost:3200/"
      acceptable_op_urls:
      - "http://localhost:3200/server"

test:
  skip_collaboration:
    skip_url: "http://test.openskip.org"
    secret_key: "hogehogehogehoge"
    fulltext_search:
      endpoint:  "/search/full_text_search"
      query_name: "full_text_query"
    fixed_op:
      disabled: true
      fixed_openid_server_url: "http://www.myopenid.com"
      acceptable_op_urls:
      - "http://localhost:3200/server"

