default_label:  &label_defaults
  label_defaults:
    - color: "#cccccc"
      display_name: "ラベルなし"
    - color: "#ffbbbb"
      display_name: "ラベル 1"
    - color: "#cc9999"
      display_name: "ラベル 2"
    - color: "#bbffbb"
      display_name: "ラベル 3"
    - color: "#99cc99"
      display_name: "ラベル 4"
    - color: "#bbbbff"
      display_name: "ラベル 5"
    - color: "#9999cc"
      display_name: "ラベル 6"
    - color: "#ffffbb"
      display_name: "ラベル 7"
    - color: "#ffbbff"
      display_name: "ラベル 8"
    - color: "#ffffbb"
      display_name: "ラベル 9"

test:
  secret_key: "hogehogehogehoge"
  skip_collabolation:
    skip_url: "http://test.openskip.org"
    fulltext_search:
      endpoint:  "http://test.openskip.org/search/full_text_search"
      query_name: "full_text_query"
  <<: *label_defaults
  fixed_op:
    disabled: true
    fixed_openid_server_url: "http://www.myopenid.com"
    acceptable_op_urls:
    - "http://localhost:3200/server"

